###### experiment name - for looking up optuna study name
experiment_name: mean_fps


###### directory where results will be written
output_dir: ./results/

###### experiment & trial time limit in seconds (5 hours / 1 hour)
experiment_time_limit: 18000
trial_time_limit: 3600


###### number of trials for hyperparameter search & optimization
n_random_trials: 30
n_opt_trials: 0
hparam_seed: 0

###### GPU parameters
use_gpu: True
gpu_ids: [0] # The 3080
data_parallel: False

###### Training parameters
batch_size: 512
val_batch_size: 256
early_stopping_rounds: 20
epochs: 500
logging_period: 100
scale_numerical_features: Quantile
impute: mean
# inject_missing: 0.3